FROM gradle:8.5-jdk21 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build -x test --no-daemon

FROM openjdk:21-slim AS production
EXPOSE 8080
RUN mkdir /app
# Accept build arguments
ARG DATABASE_HOST_DEV
ARG SPRING_DATASOURCE_USERNAME_DEV
ARG DATABASE_HOST_DEV
ARG SPRING_DATASOURCE_URL_DEV
ARG SPRING_DATASOURCE_USERNAME_DEV
ARG SPRING_DATASOURCE_PASSWORD_DEV
ARG DESIGN_PROCESSING_URL_DEV
ARG AZURE_STORAGE_CONTAINER_NAME_DEV
ARG AZURE_CONNECTION_STRING_DEV
ARG AZURE_STORAGE_CONNECTION_STRING_DEV

# Set these arguments as environment variables
ENV DATABASE_HOST_DEV=${DATABASE_HOST_DEV}
ENV SPRING_DATASOURCE_USERNAME_DEV=${SPRING_DATASOURCE_USERNAME_DEV}
ENV DATABASE_HOST_DEV=${DATABASE_HOST_DEV}
ENV SPRING_DATASOURCE_URL_DEV=${SPRING_DATASOURCE_URL_DEV}
ENV SPRING_DATASOURCE_USERNAME_DEV=${SPRING_DATASOURCE_USERNAME_DEV}
ENV SPRING_DATASOURCE_PASSWORD_DEV=${SPRING_DATASOURCE_PASSWORD_DEV}
ENV DESIGN_PROCESSING_URL_DEV=${DESIGN_PROCESSING_URL_DEV}
ENV AZURE_STORAGE_CONTAINER_NAME_DEV=${AZURE_STORAGE_CONTAINER_NAME_DEV}
ENV AZURE_CONNECTION_STRING_DEV=${AZURE_CONNECTION_STRING_DEV}
ENV AZURE_STORAGE_CONNECTION_STRING_DEV=${AZURE_STORAGE_CONNECTION_STRING_DEV}


COPY --from=build /home/gradle/src/build/libs/*.jar /app/masterdata-*.jar
ENTRYPOINT ["java","-jar","app/masterdata-*.jar"]
